export const CALCULATOR_UPDATE_DISPLAY = 'CALCULATOR_UPDATE_DISPLAY';
export const CALCULATOR_CLEAR_KEY = 'CALCULATOR_CLEAR_KEY';
export const CALCULATOR_CLEAR_ALL = 'CALCULATOR_CLEAR_ALL';
export const CALCULATOR_EQUAL = 'CALCULATOR_EQUAL';

export const HISTORY_ADD = 'ADD_HISTORY';
export const HISTORY_CLEAR_EXPRESSION = 'HISTORY_CLEAR_EXPRESSION';
export const HISTORY_CLEAR_ALL = 'HISTORY_CLEAR_ALL';
